In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

In [2]:
%matplotlib inline 

In [3]:
dataset = pd.read_csv('Tweets.csv')

In [4]:
dataset

4      3  Mon May 11 03:17:40 UTC 2009  kindle2           tpryan  \
0    4      4  Mon May 11 03:18:03 UTC 2009  kindle2           vcu451   
1    4      5  Mon May 11 03:18:54 UTC 2009  kindle2           chadfu   
2    4      6  Mon May 11 03:19:04 UTC 2009  kindle2            SIX15   
3    4      7  Mon May 11 03:21:41 UTC 2009  kindle2         yamarama   
4    4      8  Mon May 11 03:22:00 UTC 2009  kindle2     GeorgeVHulme   
..  ..    ...                           ...      ...              ...   
492  2  14072  Sun Jun 14 04:31:43 UTC 2009    latex          proggit   
493  0  14073  Sun Jun 14 04:32:17 UTC 2009    latex           sam33r   
494  4  14074  Sun Jun 14 04:36:34 UTC 2009    latex  iamtheonlyjosie   
495  0  14075  Sun Jun 14 21:36:07 UTC 2009     iran        plutopup7   
496  0  14076  Sun Jun 14 21:36:17 UTC 2009     iran     captain_pete   

    @stellargirl I loooooooovvvvvveee my Kindle2. Not that the DX is cool, but the 2 is fantastic in its own right.  
0    Reading my kindle2...  Love it... Lee childs i...                                                               
1    Ok, first assesment of the #kindle2 ...it fuck...                                                               
2    @kenburbary You'll love your Kindle2. I've had...                                                               
3    @mikefish  Fair enough. But i have the Kindle2...                                                               
4    @richardebaker no. it is too big. I'm quite ha...                                                               
..                                                 ...                                                               
492  Ask Programming: LaTeX or InDesign?: submitted...                                                               
493  On that note, I hate Word. I hate Pages. I hat...                                                               
494  Ahhh... back in a *real* text editing environm...                                                               
495  Trouble in Iran, I see. Hmm. Iran. Iran so far...                                                               
496  Reading the tweets coming out of Iran... The w...                                                               

[497 rows x 6 columns]

The received source data does not have headers. The next step will be to add them using the pandas library.

In [5]:
dataset = pd.read_csv('Tweets.csv', header=None)
header = ['Sentiment', 'The id of the tweet', 'The date of the tweet', 'The query', 'The user that tweeted', 'The text of the tweet']
dataset.columns = header

In [6]:
dataset

Sentiment  The id of the tweet         The date of the tweet The query  \
0            4                    3  Mon May 11 03:17:40 UTC 2009   kindle2   
1            4                    4  Mon May 11 03:18:03 UTC 2009   kindle2   
2            4                    5  Mon May 11 03:18:54 UTC 2009   kindle2   
3            4                    6  Mon May 11 03:19:04 UTC 2009   kindle2   
4            4                    7  Mon May 11 03:21:41 UTC 2009   kindle2   
..         ...                  ...                           ...       ...   
493          2                14072  Sun Jun 14 04:31:43 UTC 2009     latex   
494          0                14073  Sun Jun 14 04:32:17 UTC 2009     latex   
495          4                14074  Sun Jun 14 04:36:34 UTC 2009     latex   
496          0                14075  Sun Jun 14 21:36:07 UTC 2009      iran   
497          0                14076  Sun Jun 14 21:36:17 UTC 2009      iran   

    The user that tweeted                              The text of the tweet  
0                  tpryan  @stellargirl I loooooooovvvvvveee my Kindle2. ...  
1                  vcu451  Reading my kindle2...  Love it... Lee childs i...  
2                  chadfu  Ok, first assesment of the #kindle2 ...it fuck...  
3                   SIX15  @kenburbary You'll love your Kindle2. I've had...  
4                yamarama  @mikefish  Fair enough. But i have the Kindle2...  
..                    ...                                                ...  
493               proggit  Ask Programming: LaTeX or InDesign?: submitted...  
494                sam33r  On that note, I hate Word. I hate Pages. I hat...  
495       iamtheonlyjosie  Ahhh... back in a *real* text editing environm...  
496             plutopup7  Trouble in Iran, I see. Hmm. Iran. Iran so far...  
497          captain_pete  Reading the tweets coming out of Iran... The w...  

[498 rows x 6 columns]

Next, it is necessary to remove columns that will not be useful for training the model and verify if the columns have values in the appropriate format.

In [7]:
dataset.drop(['The id of the tweet', 'The date of the tweet', 'The query', 'The user that tweeted'], axis = 1, inplace = True)

In [8]:
dataset

Sentiment                              The text of the tweet
0            4  @stellargirl I loooooooovvvvvveee my Kindle2. ...
1            4  Reading my kindle2...  Love it... Lee childs i...
2            4  Ok, first assesment of the #kindle2 ...it fuck...
3            4  @kenburbary You'll love your Kindle2. I've had...
4            4  @mikefish  Fair enough. But i have the Kindle2...
..         ...                                                ...
493          2  Ask Programming: LaTeX or InDesign?: submitted...
494          0  On that note, I hate Word. I hate Pages. I hat...
495          4  Ahhh... back in a *real* text editing environm...
496          0  Trouble in Iran, I see. Hmm. Iran. Iran so far...
497          0  Reading the tweets coming out of Iran... The w...

[498 rows x 2 columns]

In [9]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 498 entries, 0 to 497
Data columns (total 2 columns):
 #   Column                 Non-Null Count  Dtype 
---  ------                 --------------  ----- 
 0   Sentiment              498 non-null    int64 
 1   The text of the tweet  498 non-null    object
dtypes: int64(1), object(1)
memory usage: 7.9+ KB


After cleaning the data, it is necessary to prepare the bag of words.

In [10]:
import re
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer


[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\micha\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [11]:
print(stopwords.words('english'))

['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', '

When analyzing the sentiment of tweets (positive/neutral/negative), it is also important to consider words such as "not" and "no". Therefore, these words are excluded from the list of stopwords.

In [12]:
corpus = []
for i in range(0, 498):
  tweet = re.sub('[^a-zA-Z]', ' ', dataset['The text of the tweet'][i])
  tweet = tweet.lower()
  tweet = tweet.split()
  ps = PorterStemmer()
  all_stopwords = stopwords.words('english')
  all_stopwords.remove('not')
  all_stopwords.remove('no')
  tweet = [ps.stem(word) for word in tweet if not word in set(all_stopwords)]
  tweet = ' '.join(tweet)
  corpus.append(tweet)

In [13]:
print(corpus)

['stellargirl loooooooovvvvvvee kindl not dx cool fantast right', 'read kindl love lee child good read', 'ok first asses kindl fuck rock', 'kenburbari love kindl mine month never look back new big one huge no need remors', 'mikefish fair enough kindl think perfect', 'richardebak no big quit happi kindl', 'fuck economi hate aig non loan given ass', 'jqueri new best friend', 'love twitter', 'not love obama make joke', 'check video presid obama white hous correspond dinner http bit ly imxum', 'karoli firmli believ obama pelosi zero desir civil charad slogan want destroy conservat', 'hous correspond dinner last night whoopi barbara amp sherri went obama got stand ovat', 'watchin espn ju seen new nike commer puppet lebron sh hilari lmao', 'dear nike stop flywir shit wast scienc ugli love vincentx x', 'lebron best athlet gener not time basketbal relat want get inter sport debat', 'talk guy last night tell die hard spur fan also told hate lebron jame', 'love lebron http bit ly pdhur', 'ludaju

In [14]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
X = cv.fit_transform(corpus).toarray()
y = dataset.iloc[:, 0].values

In [15]:
len(X[0])

1871

The specific language used by Twitter users requires the inclusion of all words in the model. Therefore, the exclusion of rarely used words using the max_features parameter of the CountVectorizer class is not applied.

The nature of the analyzed data supports the choice of a classification model. The methodology for finding the most accurate model will be as follows:

1. Training classification models,
2. Checking the accuracy score for the tested model,
3. Verification using cross-validation score to assess the accuracy of the result obtained from the accuracy score analysis and determine the value of the standard deviation.

Splitting into training data and test data.

In [16]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)

LogisticRegression

In [17]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

LogisticRegression(random_state=0)

In [18]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[17  6  6]
 [ 6 20  9]
 [ 6  5 25]]


0.62

In [19]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)
print("Accuracy: {:.2f}%".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f}%".format(accuracies.std()*100))

Accuracy: 72.60%
Standard Deviation: 6.86%


KNeighborsClassifier

In [20]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)

KNeighborsClassifier()

In [21]:
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[17  6  6]
 [11 11 13]
 [ 6 10 20]]


0.48

In [22]:
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)
print("Accuracy: {:.2f}%".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f}%".format(accuracies.std()*100))

Accuracy: 51.01%
Standard Deviation: 7.15%


Support Vector Machine

In [23]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'linear', random_state = 0)
classifier.fit(X_train, y_train)

SVC(kernel='linear', random_state=0)

In [24]:
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[15  6  8]
 [ 3 21 11]
 [ 7  4 25]]


0.61

In [25]:
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)
print("Accuracy: {:.2f}%".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f}%".format(accuracies.std()*100))

Accuracy: 68.83%
Standard Deviation: 8.40%


Kernel Support Vector Machine

In [26]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf', random_state = 0)
classifier.fit(X_train, y_train)

SVC(random_state=0)

In [27]:
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[18  5  6]
 [11 13 11]
 [ 7  4 25]]


0.56

In [28]:
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)
print("Accuracy: {:.2f}%".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f}%".format(accuracies.std()*100))

Accuracy: 70.07%
Standard Deviation: 9.31%


Naive Bayes

In [29]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB()

In [30]:
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[19  6  4]
 [ 8 17 10]
 [ 3  5 28]]


0.64

In [31]:
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)
print("Accuracy: {:.2f}%".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f}%".format(accuracies.std()*100))

Accuracy: 63.60%
Standard Deviation: 8.06%


Decision Tree Classification

In [32]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [33]:
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[21  6  2]
 [ 8 23  4]
 [ 7  5 24]]


0.68

In [34]:
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)
print("Accuracy: {:.2f}%".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f}%".format(accuracies.std()*100))

Accuracy: 65.34%
Standard Deviation: 6.23%


Random Forest Classification

In [35]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

In [36]:
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[13  4 12]
 [ 7 18 10]
 [ 6  6 24]]


0.55

In [37]:
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)
print("Accuracy: {:.2f}%".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f}%".format(accuracies.std()*100))

Accuracy: 67.56%
Standard Deviation: 8.89%


The last model will be XGBoost. Before training the model, it is necessary to modify the source data by changing the values in the 'Sentiment' column from '0, 2, 4' to '0, 1, 2'.

In [38]:
dataset['Sentiment'] = dataset['Sentiment'].replace({0: 0, 2: 1, 4: 2})
y = dataset.iloc[:, 0].values
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)

In [39]:
from xgboost import XGBClassifier
classifier = XGBClassifier()
classifier.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              n_estimators=100, n_jobs=None, num_parallel_tree=None,
              objective='multi:softprob', predictor=None, ...)

In [40]:
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[18  6  5]
 [ 6 20  9]
 [ 8  7 21]]


0.59

In [41]:
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)
print("Accuracy: {:.2f}%".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f}%".format(accuracies.std()*100))

Accuracy: 68.06%
Standard Deviation: 6.24%


Due to the specific vocabulary used by Twitter users, it is challenging to train a model that can accurately determine the sentiment of a tweet (positive/neutral/negative).